<a href="https://colab.research.google.com/github/leejsya/MLProgramming/blob/main/MPG_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import pandas as pd

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler

In [48]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/auto+mpg/auto-mpg.data-original',
                 sep='\s+',
                 names=[
                     'mpg', 'cylinders','displacement','horsepower','weight','acceleration','model year','origin','car name'
                 ])

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipykernel_4692/474827913.py:2: SyntaxWarning: invalid escape sequence '\s'
  sep='\s+',

In [49]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8.0,307.0,130.0,3504.0,12.0,70.0,1.0,chevrolet chevelle malibu
1,15.0,8.0,350.0,165.0,3693.0,11.5,70.0,1.0,buick skylark 320
2,18.0,8.0,318.0,150.0,3436.0,11.0,70.0,1.0,plymouth satellite
3,16.0,8.0,304.0,150.0,3433.0,12.0,70.0,1.0,amc rebel sst
4,17.0,8.0,302.0,140.0,3449.0,10.5,70.0,1.0,ford torino

In [50]:
df = df.dropna()
X = df.drop(['origin','car name', 'mpg'], axis=1)
y = df['mpg']

print(X)
print('\n')
print(y)

     cylinders  displacement  horsepower  weight  acceleration  model year
0          8.0         307.0       130.0  3504.0          12.0        70.0
1          8.0         350.0       165.0  3693.0          11.5        70.0
2          8.0         318.0       150.0  3436.0          11.0        70.0
3          8.0         304.0       150.0  3433.0          12.0        70.0
4          8.0         302.0       140.0  3449.0          10.5        70.0
..         ...           ...         ...     ...           ...         ...
401        4.0         140.0        86.0  2790.0          15.6        82.0
402        4.0          97.0        52.0  2130.0          24.6        82.0
403        4.0         135.0        84.0  2295.0          11.6        82.0
404        4.0         120.0        79.0  2625.0          18.6        82.0
405        4.0         119.0        82.0  2720.0          19.4        82.0

[392 rows x 6 columns]


0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
401    27.0
402    44.0
403    32.0
404    28.0
405    31.0
Name: mpg, Length: 392, dtype: float64

In [51]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

In [53]:
DT_model = DecisionTreeRegressor()
RF_model = RandomForestRegressor()
LR_model = LinearRegression()

In [54]:
DT_model.fit(X_train, y_train)
RF_model.fit(X_train, y_train)
LR_model.fit(X_train, y_train)

LinearRegression()

In [55]:
DT_y_pred = DT_model.predict(X_test)
RF_y_pred = RF_model.predict(X_test)
LR_y_pred = LR_model.predict(X_test)

In [57]:
print(f"DT:\n {mean_squared_error(DT_y_pred, y_test)}\n")
print(f"RF:\n {mean_squared_error(RF_y_pred, y_test)}\n")
print(f"LR:\n {mean_squared_error(LR_y_pred, y_test)}\n")

DT:
 16.960379746835446

RF:
 8.73749041772151

LR:
 17.059667965003275